; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = m5stack_atom_mcp2515
src_dir = ./

[env]
monitor_speed = 115200
lib_deps =
	https://github.com/MaSiRoProjectOSS/CushyWebServer
lib_compat_mode = strict
lib_ldf_mode = chain
build_src_filter =
	+<src/>
build_flags =
	-D OUTPUT_MESSAGE_FOR_SERIAL=1
	-D SETTING_SYSTEM_NAME="\"CAN Data Viewer\""
	-D DEBUG_MODE=0
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
	-D SETTING_WIFI_HOSTNAME="\"\""
check_tool = cppcheck, clangtidy
check_flags = --enable=all
platform_packages = tool-cppcheck
check_src_filters =
	-<.pio/>
	+<src\>
	+<include\>
	+<examples\>
	-<.git\>
	-<.svn\>
	-<.pio\>
	-<.vscode\>
	-<data\>
	-<doxygen\>
	-<test\>


[env:m5stack_atom_mcp2515]
platform = espressif32
framework = arduino
board = m5stack-atom
lib_deps =
	m5stack/M5Atom
	fastled/FastLED
	coryjfowler/mcp_can@^1.5.0
	${env.lib_deps}
lib_ignore =
  RPAsyncTCP
  ESPAsyncTCP
build_src_filter =
	${env.build_src_filter}
	+<examples/basic>
build_flags =
	${env.build_flags}
	-D LIB_CAN_DRIVER=1
